pipeline:

  release_server:
    image: plugins/ecr
    repo: devops/aliyun-aws-tunnel-monitor
    secrets: [ ecr_access_key, ecr_secret_key ]
    default_tags: true
    environment:
      - ECR_CREATE_REPOSITORY=true
      - ECR_REGION=ap-southeast-1
    when:
      event: tag
