pipeline:

  push-docker-tags:
    image: plugins/docker
    repo: redmart/prometheusrules-validator
    auto_tag: true
    dry-run: true
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

