pipeline:

  push-docker-tags:
    image: plugins/docker
    repo: redmart/prometheusrules-validator
    auto_tag: true
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  docker-build-pr:
    image: plugins/docker
    repo: redmart/prometheusrules-validator
    dry_run: true
    auto_tag: true
    when:
      event: pull_request


